import { StyleSheet } from 'react-native';
import { C } from '@/theme/colors';
import { F } from '@/theme/typography';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingBottom: 14,
    backgroundColor: C.white,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
    gap: 10,
  },
  backBtn: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: C.surface,
  },
  headerTitle: { flex: 1, fontSize: 17, fontFamily: F.bold, color: C.ink },
  headerActions: { flexDirection: 'row', alignItems: 'center' },
  headerActionBtn: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shareBtn: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Video
  videoContainer: { width: '100%', height: 220, overflow: 'hidden' },
  videoGradient: { flex: 1, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  stripeOverlay: { ...StyleSheet.absoluteFillObject, overflow: 'hidden' },
  stripe: {
    position: 'absolute',
    left: -200,
    right: -200,
    height: 18,
    backgroundColor: 'rgba(255,255,255,0.04)',
    transform: [{ rotate: '-35deg' }],
  },
  playBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(255,255,255,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 4,
  },
  durationBadge: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    backgroundColor: 'rgba(0,0,0,0.75)',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  durationText: { fontSize: 12, fontFamily: F.bold, color: '#fff' },

  // File banner
  fileBanner: {
    height: 160,
    backgroundColor: C.amber100,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  fileBannerIcon: {
    width: 64,
    height: 64,
    borderRadius: 18,
    backgroundColor: C.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fileBannerLabel: { fontSize: 15, fontFamily: F.bold, color: C.warn },
  fileBannerSub: { fontSize: 12, fontFamily: F.regular, color: C.warn700 },

  // Doc banner
  docBanner: { width: '100%', height: 160, overflow: 'hidden' },
  docBannerGradient: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 10 },
  docBannerText: { fontSize: 14, fontFamily: F.bold, color: 'rgba(255,255,255,0.7)', letterSpacing: 1 },

  // Content
  content: { padding: 20, gap: 12 },
  catBadge: { alignSelf: 'flex-start', paddingHorizontal: 12, paddingVertical: 5, borderRadius: 20 },
  catBadgeText: { fontSize: 13, fontFamily: F.semiBold },
  title: { fontSize: 22, fontFamily: F.extraBold, color: C.ink, lineHeight: 30 },
  desc: { fontSize: 14, fontFamily: F.regular, color: C.sec, lineHeight: 22 },
  updatedText: { fontSize: 12, fontFamily: F.regular, color: C.mut },

  // Actions
  actionRow: { flexDirection: 'row', gap: 10, marginTop: 4 },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 13,
    borderRadius: 14,
  },
  actionText: { fontSize: 14, fontFamily: F.semiBold },

  // Section
  section: { gap: 10, marginTop: 6 },
  sectionLabel: { fontSize: 15, fontFamily: F.bold, color: C.ink },

  // Files
  fileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: C.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  fileIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: C.teal100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fileName: { fontSize: 13, fontFamily: F.semiBold, color: C.ink },
  fileSize: { fontSize: 11, fontFamily: F.regular, color: C.mut, marginTop: 2 },

  // Comments
  commentRow: { flexDirection: 'row', gap: 12, paddingVertical: 12 },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: C.surface,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  avatarText: { fontSize: 12, fontFamily: F.bold, color: C.sec },
  commentMeta: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 3 },
  commentName: { fontSize: 13, fontFamily: F.bold, color: C.ink },
  commentTime: { fontSize: 12, fontFamily: F.regular, color: C.mut },
  commentText: { fontSize: 13, fontFamily: F.regular, color: C.sec, lineHeight: 19 },
  divider: { height: 1, backgroundColor: C.line, marginLeft: 50 },

  // Input bar
  inputBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 18,
    paddingTop: 12,
    backgroundColor: C.white,
    borderTopWidth: 1,
    borderTopColor: C.line,
  },
  commentInput: {
    flex: 1,
    height: 44,
    backgroundColor: C.surface,
    borderRadius: 22,
    paddingHorizontal: 16,
    fontSize: 14,
    fontFamily: F.regular,
    color: C.ink,
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Edit modal
  editOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  editSheet: {
    width: '100%',
    maxHeight: '85%',
    backgroundColor: C.white,
    borderRadius: 18,
    padding: 18,
    gap: 12,
  },
  editScroll: { maxHeight: 420 },
  editTitleLabel: { fontSize: 16, fontFamily: F.extraBold, color: C.ink },
  editInput: {
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 12,
    paddingHorizontal: 14,
    height: 46,
    fontSize: 14,
    fontFamily: F.medium,
    color: C.ink,
  },
  editSelectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: C.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    paddingHorizontal: 14,
    height: 46,
  },
  editSelectText: { fontSize: 14, fontFamily: F.regular, color: C.ink, flex: 1 },
  editFieldLabel: { fontSize: 12.5, fontFamily: F.bold, color: C.sec, marginTop: 2 },
  editUploadButtons: { flexDirection: 'row', gap: 8 },
  editUploadBtn: {
    flex: 1,
    alignItems: 'center',
    gap: 5,
    paddingVertical: 9,
    borderRadius: 11,
    backgroundColor: C.surface,
  },
  editUploadBtnIcon: {
    width: 32,
    height: 32,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editUploadBtnLabel: { fontSize: 10.5, fontFamily: F.semiBold, color: C.sec },
  editUploadList: { gap: 6 },
  editUploadItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: C.surface,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  editUploadItemName: { flex: 1, fontSize: 12.5, fontFamily: F.regular, color: C.ink },
  editTextarea: {
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 12,
    fontSize: 14,
    fontFamily: F.regular,
    color: C.ink,
    minHeight: 90,
  },
  editPoinContainer: {
    backgroundColor: C.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    overflow: 'hidden',
  },
  editPoinRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  editPoinBullet: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  editPoinBulletText: { fontSize: 10, fontFamily: F.bold, color: '#fff' },
  editPoinInput: {
    flex: 1,
    fontSize: 13.5,
    fontFamily: F.regular,
    color: C.ink,
    height: 34,
  },
  editAddPoinBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  editAddPoinText: { fontSize: 12.5, fontFamily: F.semiBold, color: C.teal },
  poinViewRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingVertical: 4 },
  poinViewBullet: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    marginTop: 1,
  },
  poinViewBulletText: { fontSize: 10, fontFamily: F.bold, color: '#fff' },
  poinViewText: { flex: 1, fontSize: 13.5, fontFamily: F.regular, color: C.sec, lineHeight: 20 },
  editBtnRow: { flexDirection: 'row', gap: 10, marginTop: 4 },
  editCancelBtn: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.surface,
  },
  editCancelText: { fontSize: 14, fontFamily: F.bold, color: C.sec },
  editSaveBtn: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.teal,
  },
  editSaveText: { fontSize: 14, fontFamily: F.bold, color: '#fff' },

  // Jenis picker sheet
  sheetOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15,23,42,0.72)',
    justifyContent: 'flex-end',
  },
  sheetContainer: {
    backgroundColor: C.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 18,
    paddingTop: 0,
    gap: 6,
  },
  sheetHandleArea: { alignItems: 'center', paddingVertical: 12 },
  sheetHandle: { width: 40, height: 4, borderRadius: 2, backgroundColor: C.line },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  sheetTitle: { fontSize: 17, fontFamily: F.bold, color: C.ink },
  sheetOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1.5,
    borderColor: C.line,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: C.white,
  },
  sheetRadio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: C.line,
    backgroundColor: C.white,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  sheetRadioDot: { width: 10, height: 10, borderRadius: 5 },
  sheetOptionText: { flex: 1, fontSize: 14, fontFamily: F.regular, color: C.ink },
});
