import { StyleSheet } from 'react-native';
import { C } from '@/theme/colors';
import { F } from '@/theme/typography';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg },
  overlayBg: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15,23,42,0.82)',
    justifyContent: 'flex-end',
  },
  qaPanel: { paddingHorizontal: 18, gap: 10 },
  qaLabel: {
    fontSize: 11,
    fontFamily: F.bold,
    color: 'rgba(255,255,255,0.6)',
    letterSpacing: 1.2,
    marginBottom: 2,
  },
  qaCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.white,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 14,
  },
  qaIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  qaBody: { flex: 1 },
  qaTitle: { fontSize: 14, fontFamily: F.semiBold, color: C.ink },
  qaSub: { fontSize: 12, fontFamily: F.regular, color: C.mut, marginTop: 1 },
  fab: {
    position: 'absolute',
    right: 20,
    borderRadius: 18,
    overflow: 'hidden',
    shadowColor: '#10b981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  fabGradient: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fabDark: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1e293b',
  },
  headerSearch: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerSearchInput: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.55)',
    paddingHorizontal: 12,
    gap: 8,
    height: 36,
  },
  headerSearchText: {
    flex: 1,
    fontSize: 13,
    fontFamily: F.regular,
    color: '#fff',
    height: 36,
  },
  scroll: { flex: 1 },
  scrollContent: { paddingBottom: 32 },
  moduleTabs: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  moduleTab: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: C.white,
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: C.line,
    shadowColor: C.ink,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  moduleIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 7,
  },
  moduleLabel: { fontSize: 12, fontFamily: F.semiBold, color: C.sec },
  catRow: { paddingHorizontal: 18, paddingBottom: 12, gap: 8 },
  catChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.line,
  },
  catChipActive: { backgroundColor: C.teal, borderColor: C.teal },
  catText: { fontSize: 13, fontFamily: F.semiBold, color: C.sec },
  catTextActive: { color: '#fff' },
  docList: { paddingHorizontal: 18, gap: 10 },
  empty: { alignItems: 'center', paddingVertical: 48, gap: 12 },
  emptyText: { fontSize: 14, color: C.mut },
  docCard: {
    backgroundColor: C.white,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: C.line,
    shadowColor: C.ink,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  docTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  badge: { paddingHorizontal: 9, paddingVertical: 3, borderRadius: 20 },
  badgeText: { fontSize: 11, fontFamily: F.bold },
  catBadge: {
    paddingHorizontal: 9,
    paddingVertical: 3,
    borderRadius: 20,
    backgroundColor: C.surface,
  },
  catBadgeText: { fontSize: 11, fontFamily: F.semiBold, color: C.sec },
  docTitle: { fontSize: 15, fontFamily: F.extraBold, color: C.ink, lineHeight: 21 },
  docDivider: { height: 1, backgroundColor: C.line, marginVertical: 12 },
  docFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  docMeta: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  docUpdated: { fontSize: 12, fontFamily: F.regular, color: C.mut },
  docStatsRow: { flexDirection: 'row', gap: 14 },
  docStatItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  docStatText: { fontSize: 12, fontFamily: F.semiBold, color: C.mut },
});
