import React from 'react';
import {
  IconHome,
  IconFileText,
  IconFilePlus,
  IconFolder,
  IconDotsCircleHorizontal,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUpRight,
  IconArrowDownRight,
  IconBell,
  IconBellOff,
  IconSearch,
  IconMapPin,
  IconChevronRight,
  IconChevronLeft,
  IconChevronDown,
  IconAlertTriangle,
  IconCalendar,
  IconClipboard,
  IconCheck,
  IconCircleCheck,
  IconX,
  IconPlus,
  IconDownload,
  IconUser,
  IconUsers,
  IconLock,
  IconLogout,
  IconAdjustments,
  IconPencil,
  IconEye,
  IconDeviceFloppy,
  IconShield,
  IconSettings,
  IconFilter,
  IconTrendingUp,
  IconTrendingDown,
  IconMessage,
  IconStar,
  IconEdit,
  IconMenu2,
  IconLayoutGrid,
  IconInfoCircle,
  IconCircleX,
  IconRefresh,
  IconBook,
  IconList,
  IconPlayerPlay,
  IconMessageCircle,
  IconChartBar,
  IconDatabase,
  IconHelpCircle,
  IconActivity,
  IconBolt,
  IconClock,
  IconTag,
  IconAlertCircle,
  IconPhone,
  IconMail,
  IconCamera,
  IconPhoto,
  IconTrash,
  IconShare,
  IconLink,
  IconCopy,
  IconExternalLink,
} from '@tabler/icons-react-native';

const ICON_MAP: Record<string, React.ComponentType<any>> = {
  home: IconHome,
  'file-text': IconFileText,
  'file-plus': IconFilePlus,
  folder: IconFolder,
  'more-horizontal': IconDotsCircleHorizontal,
  'arrow-left': IconArrowLeft,
  'arrow-right': IconArrowRight,
  'arrow-up-right': IconArrowUpRight,
  'arrow-down-right': IconArrowDownRight,
  bell: IconBell,
  'bell-off': IconBellOff,
  search: IconSearch,
  'map-pin': IconMapPin,
  'chevron-right': IconChevronRight,
  'chevron-left': IconChevronLeft,
  'chevron-down': IconChevronDown,
  'alert-triangle': IconAlertTriangle,
  calendar: IconCalendar,
  clipboard: IconClipboard,
  check: IconCheck,
  'check-circle': IconCircleCheck,
  x: IconX,
  'x-circle': IconCircleX,
  plus: IconPlus,
  download: IconDownload,
  user: IconUser,
  users: IconUsers,
  lock: IconLock,
  'log-out': IconLogout,
  sliders: IconAdjustments,
  'edit-2': IconPencil,
  eye: IconEye,
  save: IconDeviceFloppy,
  shield: IconShield,
  settings: IconSettings,
  filter: IconFilter,
  'trending-up': IconTrendingUp,
  'trending-down': IconTrendingDown,
  message: IconMessage,
  star: IconStar,
  edit: IconEdit,
  menu: IconMenu2,
  grid: IconLayoutGrid,
  info: IconInfoCircle,
  refresh: IconRefresh,
  'book-open': IconBook,
  list: IconList,
  'play-circle': IconPlayerPlay,
  'message-circle': IconMessageCircle,
  'bar-chart-2': IconChartBar,
  database: IconDatabase,
  'help-circle': IconHelpCircle,
  activity: IconActivity,
  zap: IconBolt,
  clock: IconClock,
  tag: IconTag,
  'alert-circle': IconAlertCircle,
  phone: IconPhone,
  mail: IconMail,
  camera: IconCamera,
  image: IconPhoto,
  trash: IconTrash,
  share: IconShare,
  link: IconLink,
  copy: IconCopy,
  'external-link': IconExternalLink,
};

interface Props {
  name: string;
  size?: number;
  color?: string;
  style?: any;
}

export default function Icon({ name, size = 20, color = '#0F172A', style }: Props) {
  const TablerIcon = ICON_MAP[name] ?? IconAlertTriangle;
  return <TablerIcon size={size} color={color} style={style} strokeWidth={1.8} />;
}
